@startuml

/'
	definitions:
		- underline: primary key
		- bold: unique
		- strike-through: deprecated
'/

!define entity(x) class x << (E,#FFAAAA) >>
!define PK(x) <u>x</u>
!define unique(x) <b>x</b>
!define deprecated(x) <s>x</s>
'hide circle
hide methods
hide stereotypes
show <<Entity>> stereotype

title Qloud Simulator\n\
Entity Relationship Model\n\

' diagram orientation
'top to bottom direction
left to right direction

/'
	entities
'/

entity(Session) {
  PK(sid)
  server
  partner
  key
  user
}

entity(Event) {
  PK(sensorUuid)
  expiresAt
}

entity(Sensor)  {
  PK(uuid)
  unique(code)
  description
  model
  recvIntervall
  recvTime
  batteryOk
}

entity(User) {
  PK(uuid)
  unique(email)
  userName
  firstName
  lastName
  displayName
  password
  verification
  partner
}

entity(Tag) {
  PK(uuid)
  label
  foreignUse
  
}

entity(Invitation) {
  PK(uuid)
}

entity(Capability) {
  name
  type
}

entity(Policy) {
  userUuid
  policyValue
}
note bottom: policy values: {1,2,3,4}

/'
	entity relations
'/

User "1" *-- "0..N" Invitation
User "1" *-- "1" Tag : tag_all
Sensor "1" *-- "1..N" Capability
Sensor "1" *-- "1..N" Tag
Tag "1" *-- "1" User: owner
Tag "1" *-- "1..N" Policy
note top on link 
  at least 1:1 relation
  because of sensor
  owner
end note

/'
	legend
'/

legend left
|= Legend         |=  |
| E               | <<Entity>>  |
| underlined      | primary key |
| bold            | unique      |
endlegend

@enduml
